# Generated by Django 3.2.16 on 2024-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('inception_date', models.DateField()),
                ('fund_manager', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expense_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('risk_level', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('target_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('funds', models.ManyToManyField(to='home.Fund')),
            ],
        ),
    ]
