# Generated by Django 3.2.16 on 2024-09-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='expense_ratio',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_manager',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='inception_date',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='total_assets',
        ),
        migrations.AddField(
            model_name='fund',
            name='one_year_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='one_year_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='riskometer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
